#' SurvStat disease list
#'
#' @name diseases
#' @docType data
#' @references \url{https://survstat.rki.de/Content/Query/Create.aspx}
#' @keywords data
#' @export
diseases = list(
  Acinetobacter = "Acinetobacter-Infektion oder \u2013Kolonisation",      
  Adenovirus = "Adenovirus (andere Form, Meldepflichtig gem\u00e4\u00df Landesmeldeverordnung)",
  Mpox = "Affenpocken", Amoebiasis = "Amoebiasis", Arbovirus = "Arbovirus-Erkrankung",
  Astrovirus = "Astrovirus-Infektion", "Lyme Disease" = "Borreliose",
  Botulism = "Botulismus", Brucellosis = "Brucellose",
  Campylobacter = "Campylobacter-Enteritis",
  Chickungunya = "Chikungunya-Fieber",
  "Chlamydia Trachomatis" = "Chlamydia-trachomatis-Infektion",
  Cholera = "Cholera",
  CJD = "CJK",
  "Clostridium difficile / mild" = "Clostridium difficile, nicht schwerer Verlauf",
  "Clostridium difficile / moderate" = "Clostridium difficile, schwerer Verlauf", 
  "COVID-19" = "COVID-19", Cytomegalovirus = "Cytomegalie",
  Dengue = "Denguefieber", Diptheria = "Diphtherie",
  "E. Coli, enteritis" = "E.-coli-Enteritis",
  Ebola = "Ebolafieber", Echinococcosis = "Echinokokkose",
  "E. Coli, enterohemorrhagic" = "EHEC-Erkrankung",
  "Enterobacteria colonisation" = "Enterobacteriaceae-Infektion oder \u2013Kolonisation",
  Enterovirus = "Enterovirus", "Varicella, congenital" = "Fetales (kongenitales) Varizellensyndrom",
  Typhoid = "Fleckfieber", "Tick bourne encephalitis" = "FSME (Fr\u00fchsommer-Meningoenzephalitis)",
  "Gas gangrene" = "Gasbrand", "Yellow fever" = "Gelbfieber",
  Giardia = "Giardiasis", Gonorrhoea = "Gonorrhoe",
  "Group B Streptococcus" = "Gruppe-B-Streptokokken",
  "Haemophilus influenza, invasive" = "Haemophilus influenzae, invasive Erkrankung",
  "Hand foot mouth disease" = "Hand-Fu\u00df-Mund-Krankheit",
  Hantavirus = "Hantavirus-Erkrankung", "Hepatitis A" = "Hepatitis A",
  "Hepatitis B" = "Hepatitis B",
  "Hepatitis C" = "Hepatitis C",
  "Hepatitis D" = "Hepatitis D",
  "Hepatitis E" = "Hepatitis E",
  "Hepatitis non A-E" = "Hepatitis Non A-E",
  "Herpes Zoster" = "Herpes Zoster",
  HIV = "HIV-Infektion",
  "Haemolytic-uraemic syndrome" = "HUS (H\u00e4molytisch-ur\u00e4misches Syndrom), enteropathisch",
  "Influenza, seasonal" = "Influenza, saisonal",
  "Influenza, zoonotic" = "Influenza, zoonotisch",
  "Keratoconjunctivitis (IfSG)" = "Keratokunjunktivitis (Meldepflicht gem\u00e4\u00df IfSG)",
  "Keratoconjunctivitis (state)" = "Keratokunjunktivitis (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  "Whooping cough (IfSG)" = "Keuchhusten (Meldepflicht gem\u00e4\u00df IfSG)",
  "Whooping cough (state)" = "Keuchhusten (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  "Head lice" = "Kopflausbefall", Scabies = "Kr\u00e4tzmilbenbefall",
  Cryptosporidiosis = "Kryptosporidiose", "Lassa fever" = "Lassafieber",
  "Relapsing fever" = "L\u00e4user\u00fcckfallfieber",
  Legionalla = "Legionellose",
  Leprousy = "Lepra",
  Leptospirosis = "Leptospirose",
  Listeriosis = "Listeriose",
  Malaria = "Malaria",
  "Marburg virus" = "Marburgfieber",
  Measles = "Masern",
  "Meningitis (other)" = "Meningitis, andere",
  "Meningococcal, invasive" = "Meningokokken, invasive Erkrankung",
  Anthrax = "Milzbrand",
  "MRSA, invasive" = "MRSA, invasive Infektion",
  "Mumps (IfSG)" = "Mumps (Meldepflicht gem\u00e4\u00df IfSG)",
  "Mumps (state)" = "Mumps (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  Mycoplasma = "Mycoplasma",
  Norovirus = "Norovirus-Gastroenteritis",
  Orthinovirus = "Ornithose",
  Parainfluenze = "Parainfluenza",
  Paratyphus = "Paratyphus",
  Plague = "Pest",
  "Pneumococcus, invasive" = "Pneumokokken, invasive Erkrankung",
  Smallpox = "Pocken",
  Poliomyelitis = "Poliomyelitis", "Q-fever" = "Q-Fieber",
  Ringworm = "Ringelr\u00f6teln", "Rotavirus gastroenteritis" = "Rotavirus-Gastroenteritis",
  "Rubella (state)" = "R\u00f6teln (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  "Rubella, congenital" = "R\u00f6teln, konnatal",
  Rubella = "R\u00f6teln, postnatal",
  RSV = "RSV (Meldepflicht gema\u00e4\u00df IfSG)", "RSV (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  Salmonellosis = "Salmonellose",
  SARS = "SARS",
  "Scarlet fever" = "Scharlach",
  Shigellosis = "Shigellose",
  Syphilis = "Syphilis",
  Tetanus = "Tetanus",
  "Rabies (confirmed)" = "Tollwut",
  "Rabies (suspected)" = "Tollwutexpositionsverdacht",
  Toxoplasmosis = "Toxoplasmose",
  "Toxoplasmosis, congenital" = "Toxoplasmose, konnatal",
  Trichinellosis = "Trichinellose",
  Tuberculosis = "Tuberkulose",
  Tulareamia = "Tular\u00e4mie",
  "Typhoid, abdominal" = "Typhus abdominalis",
  "CJD, variant" = "vCJK",
  "Viral haemmorhagic fever" = "Virale h\u00e4morrhagische Fieber",
  "Sepsis (other)" = "Weitere bedrohliche Krankheit",
  "Gastroenteritis (other)" = "Weitere bedrohliche Krankheit (gastro)",
  Chickenpox = "Windpocken",
  "Chickenpox (state)" = "Windpocken (Meldepflicht gem\u00e4\u00df Landesmeldeverordnung)",
  Yersinia = "Yersiniose",
  Zika = "Zikavirus-Erkrankung"
)

  
#   list(
#   `Acinetobacter` = "Acinetobacter-Infektion oder –Kolonisation",
#   `Adenovirus` = "Adenovirus (andere Form, Meldepflichtig gemäß Landesmeldeverordnung)",
#   `Mpox` = "Affenpocken",
#   `Amoebiasis` = "Amoebiasis",
#   `Arbovirus` = "Arbovirus-Erkrankung",
#   `Astrovirus` = "Astrovirus-Infektion",
#   `Lyme Disease` = "Borreliose",
#   `Botulism` = "Botulismus",
#   `Brucellosis` = "Brucellose",
#   `Campylobacter` = "Campylobacter-Enteritis",
#   `Chickungunya` = "Chikungunya-Fieber",
#   `Chlamydia Trachomatis` = "Chlamydia-trachomatis-Infektion",
#   `Cholera` = "Cholera",
#   `CJD` = "CJK",
#   `Clostridium difficile / mild` = "Clostridium difficile, nicht schwerer Verlauf",
#   `Clostridium difficile / moderate` = "Clostridium difficile, schwerer Verlauf",
#   `COVID-19` = "COVID-19",
#   `Cytomegalovirus` = "Cytomegalie",
#   `Dengue` = "Denguefieber",
#   `Diptheria` = "Diphtherie",
#   `E. Coli, enteritis` = "E.-coli-Enteritis",
#   `Ebola` = "Ebolafieber",
#   `Echinococcosis` = "Echinokokkose",
#   `E. Coli, enterohemorrhagic` = "EHEC-Erkrankung",
#   `Enterobacteria colonisation` = "Enterobacteriaceae-Infektion oder –Kolonisation",
#   `Enterovirus` = "Enterovirus",
#   `Varicella, congenital` = "Fetales (kongenitales) Varizellensyndrom",
#   `Typhoid` = "Fleckfieber",
#   `Tick bourne encephalitis` = "FSME (Frühsommer-Meningoenzephalitis)",
#   `Gas gangrene` = "Gasbrand",
#   `Yellow fever` = "Gelbfieber",
#   `Giardia` = "Giardiasis",
#   `Gonorrhoea` = "Gonorrhoe",
#   `Group B Streptococcus` = "Gruppe-B-Streptokokken",
#   `Haemophilus influenza, invasive` = "Haemophilus influenzae, invasive Erkrankung",
#   `Hand foot mouth disease` = "Hand-Fuß-Mund-Krankheit",
#   `Hantavirus` = "Hantavirus-Erkrankung",
#   `Hepatitis A` = "Hepatitis A",
#   `Hepatitis B` = "Hepatitis B",
#   `Hepatitis C` = "Hepatitis C",
#   `Hepatitis D` = "Hepatitis D",
#   `Hepatitis E` = "Hepatitis E",
#   `Hepatitis non A-E` = "Hepatitis Non A-E",
#   `Herpes Zoster`= "Herpes Zoster",
#   `HIV` = "HIV-Infektion",
#   `Haemolytic-uraemic syndrome` = "HUS (Hämolytisch-urämisches Syndrom), enteropathisch",
#   `Influenza, seasonal` = "Influenza, saisonal",
#   `Influenza, zoonotic` = "Influenza, zoonotisch",
#   `Keratoconjunctivitis (IfSG)` = "Keratokunjunktivitis (Meldepflicht gemäß IfSG)",
#   `Keratoconjunctivitis (state)` = "Keratokunjunktivitis (Meldepflicht gemäß Landesmeldeverordnung)",
#   `Whooping cough (IfSG)` = "Keuchhusten (Meldepflicht gemäß IfSG)",
#   `Whooping cough (state)` = "Keuchhusten (Meldepflicht gemäß Landesmeldeverordnung)",
#   `Head lice` = "Kopflausbefall",
#   `Scabies` = "Krätzmilbenbefall",
#   `Cryptosporidiosis` = "Kryptosporidiose",
#   `Lassa fever` = "Lassafieber",
#   `Relapsing fever` = "Läuserückfallfieber",
#   `Legionalla` = "Legionellose",
#   `Leprousy` = "Lepra",
#   `Leptospirosis` = "Leptospirose",
#   `Listeriosis` = "Listeriose",
#   `Malaria` = "Malaria",
#   `Marburg virus` = "Marburgfieber",
#   `Measles` = "Masern",
#   `Meningitis (other)` = "Meningitis, andere",
#   `Meningococcal, invasive` = "Meningokokken, invasive Erkrankung",
#   `Anthrax` = "Milzbrand",
#   `MRSA, invasive` = "MRSA, invasive Infektion",
#   `Mumps (IfSG)` = "Mumps (Meldepflicht gemäß IfSG)",
#   `Mumps (state)` = "Mumps (Meldepflicht gemäß Landesmeldeverordnung)",
#   `Mycoplasma` = "Mycoplasma",
#   `Norovirus` = "Norovirus-Gastroenteritis",
#   `Orthinovirus` = "Ornithose",
#   `Parainfluenze` = "Parainfluenza",
#   `Paratyphus` = "Paratyphus",
#   `Plague` = "Pest",
#   `Pneumococcus, invasive` = "Pneumokokken, invasive Erkrankung",
#   `Smallpox` = "Pocken",
#   `Poliomyelitis` = "Poliomyelitis",
#   `Q-fever` = "Q-Fieber",
#   `Ringworm` = "Ringelröteln",
#   `Rotavirus gastroenteritis` = "Rotavirus-Gastroenteritis",
#   `Rubella (state)` = "Röteln (Meldepflicht gemäß Landesmeldeverordnung)",
#   `Rubella, congenital` = "Röteln, konnatal",
#   `Rubella` = "Röteln, postnatal",
#   `RSV` = "RSV-Infektion",
#   `Salmonellosis` = "Salmonellose",
#   `SARS` = "SARS",
#   `Scarlet fever` = "Scharlach",
#   `Shigellosis` = "Shigellose",
#   `Syphilis` = "Syphilis",
#   `Tetanus` = "Tetanus",
#   `Rabies (confirmed)` = "Tollwut",
#   `Rabies (suspected)` = "Tollwutexpositionsverdacht",
#   `Toxoplasmosis` = "Toxoplasmose",
#   `Toxoplasmosis, congenital` = "Toxoplasmose, konnatal",
#   `Trichinellosis`="Trichinellose",
#   `Tuberculosis` = "Tuberkulose",
#   `Tulareamia` = "Tularämie",
#   `Typhoid, abdominal` = "Typhus abdominalis",
#   `CJD, variant` = "vCJK",
#   `Viral haemmorhagic fever` = "Virale hämorrhagische Fieber",
#   `Sepsis (other)` = "Weitere bedrohliche Krankheit",
#   `Gastroenteritis (other)` = "Weitere bedrohliche Krankheit (gastro)",
#   `Chickenpox` = "Windpocken",
#   `Chickenpox (state)` = "Windpocken (Meldepflicht gemäß Landesmeldeverordnung)",
#   `Yersinia` = "Yersiniose",
#   `Zika` = "Zikavirus-Erkrankung"
# )


#' SurvStat age group list
#'
#' * single_year 
#' * children_coarse: from 0, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
#' * children_medium: from 0, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
#' * children_fine: from 0, 1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
#' * five_year: from 0, 1, 5, 10, 15, 20, … , 75, 80 years
#' * zero_fifteen: from 0, 15+
#' * zero_fifteen_sixty: from 0, 15, 60+
#' * zero_one_4_20_40_60_80: from 0, 15, 60+
#'
#' @name age_groups
#' @docType data
#' @references \url{https://survstat.rki.de/Content/Query/Create.aspx}
#' @keywords data
#' @export
age_groups = list(
  single_year = "[AlterPerson80].[AgeGroupName8]",
  children_coarse = "[AlterPerson80].[AgeGroupName3]", #from 0, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
  children_medium = "[AlterPerson80].[AgeGroupName2]", #from 0, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
  children_fine = "[AlterPerson80].[AgeGroupName1]", #from 0, 1, 2, 3, 4, 5, 10, 15, 20, 25, 30, 40, 50, 60, 70, 80 years
  five_year = "[AlterPerson80].[AgeGroupName6]", #from 0, 1, 5, 10, 15, 20, … , 75, 80 years
  zero_fifteen  = "[AlterPerson80].[AgeGroupName4]", #from 0, 15+
  zero_fifteen_sixty  = "[AlterPerson80].[AgeGroupName5]", #from 0, 15, 60+
  zero_one_4_20_40_60_80 = "[AlterPerson80].[AgeGroupName7]" #from 0, 15, 60+
)


